KapsamliProje.Ui/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace KapsamliProje.Ui.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Admin() //methodu admin yapıyoruz
        {
            return View();
        }

    }
}

KapsamliProje.Ui/Controllers/AuthController.cs
using KapsamliProje.Ent;
using KapsamliProje.Repos.Abstract;
using KapsamliProje.Ui.Extension;
using KapsamliProje.Ui.Models.ViewModels;
using KapsamliProje.Uow;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace KapsamliProje.Ui.Controllers
{
    public class AuthController : Controller
    {
        
        LoginModel _model;
        IUnitOfWork _unitOfWork;
        public const string Role = "Role";
        public const string UserName = "UserName"; 

        public AuthController(IUnitOfWork unitOfWork, LoginModel model)
        {
            _unitOfWork = unitOfWork;
            _model = model;
        }
        [HttpGet]
        public IActionResult Register()
        {
            return View(_model);
        }
        [HttpPost] //Bunu koymak zorundayız.
        public IActionResult Register(LoginModel model)
        {
            _unitOfWork._authRepos.Register(model.UserId, model.Password);
            return RedirectToAction("Index","Home");
        }
        [HttpGet]
        public IActionResult Login() //içerisine parametre yazmamıza gerek yok
        {
            return View("Register",_model);
        }
        [HttpPost] //Bunu koymak zorundayız.
        public IActionResult Login(LoginModel model) //Post kısmında parametrelere ihtiyacımız var
        {
            Users user =_unitOfWork._authRepos.Login(model.UserId, model.Password);
            if (user!=null)
            {
                HttpContext.Session.Set<string>(UserName,model.UserId);
                HttpContext.Session.Set<string>(Role, user.Role);
                var a=  HttpContext.Session.Get<string>(Role);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return RedirectToAction("Login");
            }
           
        }
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index","Home");
        }

    }
}

KapsamliProje.Ui/Controllers/CitiesController.cs
using KapsamliProje.Ent;
using KapsamliProje.Uow;
using Microsoft.AspNetCore.Mvc;

namespace KapsamliProje.Ui.Controllers
{
    public class CitiesController : Controller
    {
        IUnitOfWork _unitOfWork;
        Cities _cities;
        public CitiesController(IUnitOfWork Uow)
        {
            _unitOfWork = Uow;
        }


        public IActionResult List()
        {
            return View(_unitOfWork._citiesRepos.GetCitiesLists());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();

        }
        
        
        [HttpPost]
        public IActionResult Create(Cities model)
        {
            _unitOfWork._citiesRepos.Create(model);
            _unitOfWork.Save();
            return RedirectToAction("List");
        }


        [HttpGet]
        public IActionResult Edit()
        {
            return View();

        }


        [HttpPost]
        public IActionResult Edit(Cities model)
        {
            _unitOfWork._citiesRepos.Update(model);
            _unitOfWork.Save();
            return RedirectToAction("List");
        }

        [HttpGet]
        public IActionResult Delete()
        {
            return View();

        }


        [HttpPost]
        public IActionResult Delete(Cities model)
        {
            _unitOfWork._citiesRepos.Delete(model);
            _unitOfWork.Save();
            return RedirectToAction("List");
        }




    }
}

KapsamliProje.Ui/Controllers/FaturaController.cs
using KapsamliProje.Ent;
using KapsamliProje.Ui.Models;
using KapsamliProje.Uow;
using Microsoft.AspNetCore.Mvc;

namespace KapsamliProje.Ui.Controllers
{
    public class FaturaController : Controller
    {
        IUnitOfWork _unitOfWork;
        FatMaster _fatMaster;
        FatMasterModel _fmModel;
        public FaturaController(IUnitOfWork unitOfWork, FatMaster fatMaster, FatMasterModel fmModel)
        {
            _unitOfWork = unitOfWork;
            _fatMaster = fatMaster;
            _fmModel = fmModel;
        }
        public IActionResult List()
        {
            return View(_unitOfWork._fatMasterRepos.GetFatLists());
        }
        [HttpGet]
        public IActionResult Create()
        {
            _fmModel.Employees = _unitOfWork._employeesRepos.GetEmployeesSelect();
            _fmModel.Customers = _unitOfWork._customersRepos.GetCustomersSelect();
            return View(_fmModel);
        }

        [HttpPost]

        public IActionResult Create(FatMasterModel model) //sepet oluşturulurken arka planda fatmaster oluşturuluyor ve detaylar oraya giriyor.
        {
            _fatMaster.CustomerId = model.CustomerId;
            _fatMaster.EmployeeId = model.EmployeeId;
            var v = _unitOfWork._fatMasterRepos.Create(_fatMaster);
            _unitOfWork.Save();
            return RedirectToAction("Create", "FatDetail", new { id =_fatMaster.Id });
           
           
        }

    }

}

KapsamliProje.Ui/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KapsamliProje.Ui</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KapsamliProje.Ui.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KapsamliProje.Ui</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        
                          
                        @if( ViewBag.UserName!=null) //login olmuş demektir
                        {
                             <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                         </li>
                        }
                        else
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                         </li>

                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a >   
                        </li>
                           <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Fatura" asp-action="List">Fatura</a>
                            </li>
                        }
                       
                      
                        
                          <li class="text-right">
                            @if (ViewBag.UserName!=null)
                            {
                               <p>Hoşgeldiniz @ViewBag.UserName</p>  
                            }
                           
                        </li>




                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - KapsamliProje.Ui - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

KapsamliProje.Ui/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KapsamliProje.Ui</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KapsamliProje.Ui.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Admin">Admin Nav</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                      
                          
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a >     
                                </li>
                       <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="List">Categories</a>
                        </li>

                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="List">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cities" asp-action="List">Cities</a>
                        </li>

                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Counties" asp-action="List">Counties</a>
                        </li>
                        
                          <li class="text-right">
                            @if (ViewBag.UserName!=null)
                            {
                               <p>Hoşgeldiniz @ViewBag.UserName</p>  
                            }
                           
                        </li>




                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - KapsamliProje.Ui - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>